version: '3.1'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: es
      POSTGRES_PASSWORD: es
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yup
      MYSQL_DATABASE: es
      MYSQL_USER: es
      MYSQL_PASSWORD: es
    ports:
      - "3306:3306"

