version: '3.1'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: es
      POSTGRES_PASSWORD: es
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.11.2-management
    ports:
      - '5672:5672'
      - '15672:15672'

  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_MEM_DB=True
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
