version: '3.1'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: es
      POSTGRES_PASSWORD: es
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.11.2-management
    ports:
      - '5672:5672'
      - '15672:15672'

