site_name: Event Sourcery
theme:
  name: material
  palette:
    primary: deep purple
repo_url: https://github.com/python-event-sourcery/python-event-sourcery/
repo_name: python-event-sourcery/python-event-sourcery
nav:
    - 'Event Sourcery': 'index.md'
    - 'Basics': 'basics.md'
    - 'Features': 'features.md'
    - 'Tutorial - Event-Driven Architecture':
        - 'Event-Driven Architecture - Intro': 'tutorial_eda/index.md'
    - 'Tutorial - Event Sourcing':
        - 'Event Sourcing - Intro': 'tutorial_event_sourcing/index.md'
    - 'API Reference':
        - 'Event Store': 'reference/event_store.md'
        - 'StreamId': 'reference/stream_id.md'
        - 'Event': 'reference/event.md'
        - 'WrappedEvent': 'reference/wrapped_event.md'
        - 'BackendFactory': 'reference/backend_factory.md'
        - 'EventRegistry': 'reference/event_registry.md'
        - 'InMemoryBackendFactory': 'reference/in_memory_backend_factory.md'

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

